# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/charts/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/siret2idcc

deployment:
  port: ${PORT}

  livenessProbe:
    path: /healthz
    port: ${PORT}
  readinessProbe:
    path: /healthz
    port: ${PORT}

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1280Mi

  env:
    - name: PORT
      value: "${PORT}"
    - name: VERSION
      value: "${CI_COMMIT_SHORT_SHA}"

service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
    - host: "siret2idcc.fabrique.social.gouv.fr"
      paths:
        - path: /
          servicePort: ${PORT}

  tls:
    - hosts:
        - "siret2idcc.fabrique.social.gouv.fr"
      secretName: siret2idcc-certificate
